### ISSUE TITLE
Hitting stack limit?

### ISSUE THREAD

**Issue by rafkhan** [colynb/gulp-swig#25]
Hey :) This code snippet is causing something to hit the stack limit.

```
var swigSrc = 'templates/casestudy/*.html';
var swigDest = 'site/';

var swigOpts = {
  data: {
    asd: 'RAF WAS HERE'
  }
};

function swig() {
  gulp.src(swigSrc)
    .pipe(swig())
    .pipe(gulp.dest('./site/'));
}

gulp.task('deploy', deploy);
gulp.task('swig', swig);
```

and I'm getting the error

```
[18:00:49] Error: RangeError: Maximum call stack size exceeded
    at formatError (/Users/rafy/.nvm/v0.10.32/lib/node_modules/gulp/bin/gulp.js:161:10)
    at Gulp.<anonymous> (/Users/rafy/.nvm/v0.10.32/lib/node_modules/gulp/bin/gulp.js:187:15)
    at Gulp.emit (events.js:95:17)
    at Gulp.Orchestrator._emitTaskDone (/Users/rafy/Documents/rangle/rangle-website/node_modules/gulp/node_modules/orchestrator/index.js:264:8)
    at /Users/rafy/Documents/rangle/rangle-website/node_modules/gulp/node_modules/orchestrator/index.js:275:23
    at finish (/Users/rafy/Documents/rangle/rangle-website/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:21:8)
    at module.exports (/Users/rafy/Documents/rangle/rangle-website/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:36:10)
    at Gulp.Orchestrator._runTask (/Users/rafy/Documents/rangle/rangle-website/node_modules/gulp/node_modules/orchestrator/index.js:273:3)
    at Gulp.Orchestrator._runStep (/Users/rafy/Documents/rangle/rangle-website/node_modules/gulp/node_modules/orchestrator/index.js:214:10)
    at Gulp.Orchestrator.start (/Users/rafy/Documents/rangle/rangle-website/node_modules/gulp/node_modules/orchestrator/index.js:134:8)
```

Any ideas what might be wrong?

**Comment by rvaiya** [comment]
```javascript
function swig() {
  gulp.src(swigSrc)
    .pipe(swig())
    .pipe(gulp.dest('./site/'));
}
```
You have a recursive call to swig in your pipeline which never terminates :).

**Comment by rafkhan** [comment]
@rvaiya I noticed it like 5 minutes after and almost snapped my laptop in half

**Comment by rafkhan** [comment]
@rvaiya and then Kent did it too like an hour later LOL

**Comment by rvaiya** [comment]
Yo dawg, I heard you like swig with your swig so I put some swig in your swig so you can swig.
